# Generated by Django 5.2.10 on 2026-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_deadline_task_location_task_urgency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('errands', 'Errands'), ('school', 'School Help'), ('delivery', 'Delivery'), ('cleaning', 'Cleaning'), ('tech', 'Tech Help')], default='errands', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
