# Generated by Django 5.2.10 on 2026-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_category_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('errands', 'Errands'), ('delivery', 'Delivery'), ('school_help', 'School Help'), ('emergency', 'Emergency Help'), ('tech_support', 'Tech Support'), ('household', 'Household Help'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
