# Generated by Django 5.2.10 on 2026-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='barangay',
            field=models.CharField(choices=[('brgy1', 'Barangay 1 (Pob.)'), ('brgy2', 'Barangay 2 (Pob.)'), ('brgy3', 'Barangay 3 (Pob.)'), ('brgy4', 'Barangay 4 (Pob.)'), ('brgy5', 'Barangay 5 (Pob.)'), ('brgy6', 'Barangay 6 (Pob.)'), ('brgy7', 'Barangay 7 (Pob.)'), ('brgy8', 'Barangay 8 (Pob.)'), ('brgy9', 'Barangay 9 (Pob.)'), ('brgy10', 'Barangay 10 (Pob.)'), ('brgy11', 'Barangay 11 (Pob.)'), ('brgy12', 'Barangay 12 (Pob.)'), ('brgy13', 'Barangay 13 (Pob.)'), ('brgy14', 'Barangay 14 (Pob.)'), ('bocohan', 'Bocohan'), ('cotta', 'Cotta'), ('dalahican', 'Dalahican'), ('gulang', 'Gulang-Gulang'), ('ibabang_dup', 'Ibabang Dupay'), ('ibabang_iyam', 'Ibabang Iyam'), ('ibabang_talim', 'Ibabang Talim'), ('ilayang_dup', 'Ilayang Dupay'), ('ilayang_iyam', 'Ilayang Iyam'), ('ilayang_talim', 'Ilayang Talim'), ('isabang', 'Isabang'), ('mayao_castillo', 'Mayao Castillo'), ('mayao_crossing', 'Mayao Crossing'), ('mayao_kanluran', 'Mayao Kanluran'), ('mayao_parada', 'Mayao Parada'), ('mayao_silangan', 'Mayao Silangan'), ('ransohan', 'Ransohan'), ('salinas', 'Salinas'), ('talao', 'Talao-Talao')], default='brgy1', max_length=50),
        ),
    ]
